// ==== SIGAP PRAJA - UTILITAS ====
function tanggalPanjang(d){ return (d||new Date()).toLocaleDateString('id-ID',{year:'numeric',month:'long',day:'numeric'}); }
function jamSekarang(d){ return (d||new Date()).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}).replace('.',':'); }
function swalLoading(judul,teks){ Swal.fire({title:'<div class="text-xl font-black text-slate-900 mt-2">'+judul+'</div>',html:'<div class="text-[13px] text-slate-500 mt-2">'+teks+'</div>',allowOutsideClick:false,showConfirmButton:false,customClass:{popup:'rounded-[32px]'},didOpen:()=>Swal.showLoading()}); }
function swalTutup(){ Swal.close(); }
function formatWA(hp){ let s=String(hp||'').replace(/[^0-9]/g,''); if(s.startsWith('0'))s='62'+s.slice(1); else if(s.startsWith('8'))s='628'+s; return s; }
function groupHistory(list){ const g={}; (list||[]).forEach(i=>{ if(!g[i.id_laporan]) g[i.id_laporan]={id_laporan:i.id_laporan,nama_tim:i.nama_tim,tanggal:i.tanggal,link_drive:i.link_drive,link_doc:i.link_doc,waktu_mulai:i.waktu,waktu_selesai:i.waktu,temuan:[]}; g[i.id_laporan].temuan.push(i); g[i.id_laporan].waktu_selesai=i.waktu; }); return Object.values(g).reverse(); }
function wrapText(ctx,text,x,y,maxW,lh){ const w=text.split(' '); let line=''; for(let n=0;n<w.length;n++){ const t=line+w[n]+' '; if(ctx.measureText(t).width>maxW&&n>0){ ctx.fillText(line,x,y); line=w[n]+' '; y+=lh; } else line=t; } ctx.fillText(line,x,y); }
// Kompres foto + opsi timemark (jam, tanggal, alamat, watermark)
function kompresFoto(file,opt){ opt=opt||{}; return new Promise(res=>{ const r=new FileReader(); r.readAsDataURL(file); r.onload=e=>{ const img=new Image(); img.src=e.target.result; img.onload=()=>{ const MAX=opt.maxWidth||1000; const c=document.createElement('canvas'); const s=MAX/img.width; c.width=MAX; c.height=img.height*s; const ctx=c.getContext('2d'); ctx.drawImage(img,0,0,c.width,c.height);
 if(opt.timemark){ const g=ctx.createLinearGradient(0,c.height-300,0,c.height); g.addColorStop(0,'rgba(0,0,0,0)'); g.addColorStop(1,'rgba(0,0,0,0.8)'); ctx.fillStyle=g; ctx.fillRect(0,c.height-300,c.width,300); const n=new Date(); const hari=['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'][n.getDay()]; const jam=n.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}).replace('.',':'); const tgl=n.toLocaleDateString('id-ID',{day:'2-digit',month:'2-digit',year:'numeric'}); const alamat=(opt.alokasi||'Lokasi tidak diketahui'); ctx.textBaseline='bottom'; ctx.fillStyle='#fff'; ctx.font='bold 90px "Plus Jakarta Sans",sans-serif'; ctx.fillText(jam,40,c.height-130); const tw=ctx.measureText(jam).width; ctx.fillStyle='#FBBF24'; ctx.fillRect(40+tw+20,c.height-210,5,80); ctx.fillStyle='#fff'; ctx.font='30px "Plus Jakarta Sans",sans-serif'; ctx.fillText(tgl,40+tw+40,c.height-180); ctx.fillText(hari,40+tw+40,c.height-140); ctx.font='24px "Plus Jakarta Sans",sans-serif'; wrapText(ctx,alamat,40,c.height-80,c.width-100,32); ctx.textAlign='right'; ctx.fillStyle='#FBBF24'; ctx.font='bold 32px "Plus Jakarta Sans",sans-serif'; ctx.fillText('SIGAP PRAJA',c.width-40,c.height-80); ctx.fillStyle='#fff'; ctx.font='20px "Plus Jakarta Sans",sans-serif'; ctx.fillText('Foto 100% akurat',c.width-40,c.height-50); }
 res(c.toDataURL('image/jpeg',opt.quality||0.8).split(',')[1]); }; }; }); }
function gpsKunci(elLokasi,elKoordinat){ elLokasi.value='Mengunci koordinat satelit...'; if(!navigator.geolocation){ elLokasi.value='GPS tidak didukung.'; return; } navigator.geolocation.getCurrentPosition(async p=>{ const la=p.coords.latitude, lo=p.coords.longitude; elKoordinat.value=la+','+lo; try{ const r=await fetch('https://nominatim.openstreetmap.org/reverse?format=json&lat='+la+'&lon='+lo); const d=await r.json(); elLokasi.value=d.display_name||(la+','+lo); }catch(e){ elLokasi.value=la+','+lo; } },()=>{ elLokasi.value='GPS tidak merespon.'; },{enableHighAccuracy:true}); }
